
CREATE TABLE SERVICE
( 
	ID_SERVICE	serial,
	V_NAME		character varying (255) not null,
	PRIMARY KEY (ID_SERVICE)
);

CREATE TABLE TARIFF_PLAN
( 
	ID_TARIFF_PLAN	serial,
	V_NAME		character varying (255) not null,
	PRIMARY KEY (ID_TARIFF_PLAN)
);

CREATE TABLE DEPARTMENTS
( 
	ID_DEPARTMENT	serial,
	V_NAME		character varying (255) not null,
	PRIMARY KEY (ID_DEPARTMENT)
);


CREATE TABLE CONTRACTS
( 
	ID_CONTRACT_INST	serial,
	ID_DEPARTMENT		integer,
	DT_REG 			date, 
	V_EXT_IDENT		integer,
	V_STATUS		character,
	PRIMARY KEY (ID_CONTRACT_INST),	
	FOREIGN KEY (ID_DEPARTMENT) REFERENCES DEPARTMENTS (ID_DEPARTMENT)
);

CREATE TABLE BILLS
( 
	ID_BILL			serial,
	ID_CONTRACT_INST	integer,
	F_SUM 			numeric, 
	DT_EVENT 		date,
	ID_MANAGER		integer, 
	PRIMARY KEY (ID_BILL),	
	FOREIGN KEY (ID_CONTRACT_INST) REFERENCES CONTRACTS (ID_CONTRACT_INST)
);

CREATE TABLE SERVICES
( 
	ID_SERVICE_INST		serial,
	ID_CONTRACT_INST	integer,
	ID_TARIFF_PLAN 		integer,
	ID_SERVICE		integer,
	DT_START		date,
	DT_STOP 		date,
	PRIMARY KEY (ID_SERVICE_INST),	
	FOREIGN KEY (ID_CONTRACT_INST) REFERENCES CONTRACTS (ID_CONTRACT_INST),
	FOREIGN KEY (ID_TARIFF_PLAN) REFERENCES TARIFF_PLAN (ID_TARIFF_PLAN),
	FOREIGN KEY (ID_SERVICE) REFERENCES SERVICE (ID_SERVICE)
);

ALTER TABLE SERVICES
( 